# Generated by Selenium IDE
import time
import urllib.request
import hashlib
import requests
import base64
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
import time
from selenium.common.exceptions import NoSuchElementException
import threading
import sys
import cv2
f = open('android.log','a')
sys.stdout = f
sys.stderr = f
print('=======这里进入操作：'+time.strftime("%Y-%m-%d, %H:%M:%S")+'===========')
class TestFengzi():
    def setup_method(self):
        self.driver = webdriver.Edge()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def runn(self):
        QR_code = True

        while QR_code:
            print("进入判断5秒...")
            time.sleep(3)
            self.driver.refresh()
            Obtain = self.isElementPresent()
            if Obtain == True:
                QR_code = False
        else:
            return

        #定位图片在不在
    def isElementPresent(self):
        """
        用来判断元素标签是否存在，
        """
        try:
            self.driver.find_element(By.XPATH, "//*[@id='description']/div[1]/img")
        # 原文是except NoSuchElementException, e:
        except NoSuchElementException as e:
            # 发生了NoSuchElementException异常，说明页面中未找到该元素，返回False
            return False
        else:
            # 没有发生异常，表示在页面中找到了该元素，返回True
            return True
    def test_fengzi(self):
        branch = 'IfengNewsV7650'
        self.driver.implicitly_wait(10)
        self.driver.get("http://172.30.20.21:9999/login")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.ID, "j_username").click()
        self.driver.find_element(By.ID, "j_username").send_keys("ifengdev")
        self.driver.find_element(By.NAME, "j_password").send_keys("ifeng666")
        self.driver.find_element(By.NAME, "Submit").click()
        self.driver.find_element(By.LINK_TEXT, "ifengnews_android_phone").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//a[@title='Build with Parameters']").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "filter").click()
        self.driver.find_element(By.ID, "filter").send_keys(branch)
        self.driver.find_element(By.XPATH,
                                 '//*[@id="main-panel"]/form/table/tbody[15]/tr[1]/td[3]/div/input[2]').send_keys(
            "D:/pack/packconfig.txt")
        newsf1 = time.strftime("%I:%M")
        self.driver.find_element(By.XPATH, '//*[@id="yui-gen3"]').click()
        Packing_time = time.strftime("%Y-%m-%d, %H:%M:%S")
        print('提交时间',Packing_time)
        time.sleep(5)
        newsf = '//*[@id="buildHistory"]/div[2]/table/tbody/tr[2]/td/div[1]'
        element = self.driver.find_element(By.XPATH, newsf)
        element = element.get_attribute("innerText")
        element = element[1:]


        print("进入详情页成功等待300秒...")
        element = element.replace('\u200b', '')
        self.driver.get("http://172.30.20.21:9999/job/ifengnews_android_phone/" + element)
        time.sleep(300)
        # timer = threading.Timer(1, self.func)
        # timer.start()
        self.driver.refresh()

        Obtain = self.isElementPresent()
        if Obtain == False:
            self.runn()

        # 获取图片src
        element = self.driver.find_element(By.XPATH, "//*[@id='description']/div[1]/img")

        filepath = element.get_attribute("src")
        print('图片地址为：',filepath)
        # 获取div文本分支
        element = self.driver.find_element(By.XPATH, '//*[@id="main-panel"]/table/tbody/tr[4]/td[2]')
        test = element.get_attribute('innerText')
        print('获取分支为：',test)

        # 获取修改信息
        element = self.driver.find_element(By.XPATH, '//*[@id="main-panel"]/table/tbody/tr[2]/td[2]')
        modify = element.get_attribute('innerText')
        print('修改信息为：',modify)

        # 图片转md5
        urllib.request.urlretrieve(filepath, "D:/pack/temp.jpg")
        filepath1 = "D:/pack/temp.jpg"
        
        
        #二维码识别
        #解析本文中生成的第一个二维码test.jpg
        
        d=cv2.QRCodeDetector()
        val,_,_ = d.detectAndDecode(cv2.imread(filepath1))
        print('text is:',val)
        
        
        file = open(filepath1, "rb")
        md = hashlib.md5()
        md.update(file.read())
        res1 = md.hexdigest()
        print('图片md5为：',res1)
        # 图片转base64
        with open(filepath1, 'rb') as f:
            ls_f1 = base64.b64encode(f.read())
            s = ls_f1.decode()
        print('图片base64为',s)
        url1 = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22f9e9ca-b786-4d2c-875c-9c3cf8037ac4"
        mHeader1 = {'Conrtent-Type': 'application; charset=UTF-8'}
        mBody1 = {
            "msgtype": "markdown",
            "markdown": {
                "content": "\n<font color=\"warning\">安卓主线集测包</font>打包成功。\n\
                >打包时间:<font color=\"comment\">" + Packing_time + "</font>\n \
                >git版本:<font color=\"comment\">" + test + "</font>\n\
                >[内网点击下载>>]("+val+") \n\
                >修改记录:<font color=\"comment\">"+modify+"</font>"
            },
        }
        r1 = requests.post(url=url1, json=mBody1, headers=mHeader1)
        url = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22f9e9ca-b786-4d2c-875c-9c3cf8037ac4"
        mHeader = {'Conrtent-Type': 'application; charset=UTF-8'}
        mBody = {

            "msgtype": "image",
            "image": {
                "base64": s,
                "md5": res1
            }

        }
        r = requests.post(url=url, json=mBody, headers=mHeader)
        print(r1.json())
        print(r.json())
        print('======================操作完成======================')




if __name__ == "__main__":
    a = TestFengzi()
    a.setup_method()
    a.test_fengzi()
    a.teardown_method()