# Generated by Selenium IDE
import time
import urllib.request
import hashlib
import requests
import base64
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options
import time
import threading
from selenium.common.exceptions import NoSuchElementException
import sys
import cv2
f = open('iOS.log','a')
sys.stdout = f
sys.stderr = f
print('=======这里进入操作：'+time.strftime("%Y-%m-%d, %H:%M:%S")+'===========')
class TestFengzi():
    def setup_method(self):
        self.driver = webdriver.Edge()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()


    def runn(self):
        QR_code = True

        while QR_code:
            print("进入判断5秒...")
            time.sleep(2)
            self.driver.refresh()
            Obtain = self.isElementPresent()
            if Obtain == True:
                QR_code = False
        else:
            return



        # 定位图片在不在
    def isElementPresent(self):
        """
        用来判断元素标签是否存在，
        """
        try:
            self.driver.find_element(By.XPATH, "//*[@id='description']/div[1]/img")
        # 原文是except NoSuchElementException, e:
        except NoSuchElementException as e:
            # 发生了NoSuchElementException异常，说明页面中未找到该元素，返回False
            return False
        else:
            # 没有发生异常，表示在页面中找到了该元素，返回True
            return True


    def test_fengzi(self):
        branch = input('')
        self.driver.implicitly_wait(10)
        self.driver.get("http://172.30.26.23:1120/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.XPATH,'//*[@id="job_IfengNews_pods"]/td[3]/a').click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,'//*[@id="tasks"]/div[5]/span').click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,'//*[@id="filter"]').click()
        self.driver.find_element(By.XPATH, '//*[@id="filter"]').send_keys(branch)
        nbranch = 'origin/'+branch
        print(nbranch)

        self.driver.find_element(By.XPATH, '//option[@value="'+nbranch+'"]').click()
        self.driver.find_element(By.XPATH,'//*[@id="yui-gen1-button"]').click()
        Packing_time = time.strftime("%Y-%m-%d, %H:%M:%S")
        time.sleep(2)
        newsf = '//*[@id="buildHistory"]/div[2]/table/tbody/tr[2]/td/div[1]'
        element = self.driver.find_element(By.XPATH, newsf)
        element = element.get_attribute("innerText")
        element = element[1:]

        print("进入详情页成功等待600秒...")
        element = element.replace('\u200b', '')
        self.driver.get("http://172.30.26.23:1120/job/IfengNews_pods/" + element)
        time.sleep(600)

        Obtain = self.isElementPresent()
        if Obtain == False:
            self.runn()

        # 获取图片src
        element = self.driver.find_element(By.XPATH, '//*[@id="description"]/div[1]/img')

        filepath = element.get_attribute("src")
        print('获取图片地址为：',filepath)
        # 获取div文本分支
        element = self.driver.find_element(By.XPATH, '//*[@id="main-panel"]/table/tbody/tr[3]/td[2]')
        brancha = element.get_attribute('innerText')
        print('获取分支为：',brancha)

        #获取修改信息
        element = self.driver.find_element(By.XPATH, '//*[@id="main-panel"]/table/tbody/tr[1]/td[2]')
        modify = element.get_attribute('innerText')
        print('获取修改信息为：',modify)

        #处理图片
        urllib.request.urlretrieve(filepath, "D:/pack/temp1.jpg")
        filepath1 = "D:/pack/temp1.jpg"
        
        #二维码识别
        #解析本文中生成的第一个二维码test.jpg
        
        d=cv2.QRCodeDetector()
        val,_,_ = d.detectAndDecode(cv2.imread(filepath1))
        print('text is:',val)
        
        file = open(filepath1, "rb")
        md = hashlib.md5()
        md.update(file.read())
        res1 = md.hexdigest()
        print('图片md5：',res1)
        # 图片转base64
        with open(filepath1, 'rb') as f:
            ls_f1 = base64.b64encode(f.read())
            s = ls_f1.decode()
        print('图片base64：',s)
        #https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=177a3d48-76cd-4f43-b00b-63122d16d3f2
        url1 = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a091f4df-080d-4b48-8bb7-6506f9f99a81"
        mHeader1 = {'Conrtent-Type': 'application; charset=UTF-8'}
        mBody1 = {
            "msgtype": "markdown",
            "markdown": {
                "content": "\n<font color=\"warning\">iOS主线集测包</font>打包成功。\n\
                >打包时间:<font color=\"comment\">"+Packing_time+"</font>\n \
                >git版本:<font color=\"comment\">"+brancha+"</font>\n\
                >[外网点击下载>>]("+val+") \n\
                >修改记录:<font color=\"comment\">"+modify+"</font>"
            },
        }
        r1 = requests.post(url=url1, json=mBody1, headers=mHeader1)
        url = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a091f4df-080d-4b48-8bb7-6506f9f99a81"
        mHeader = {'Conrtent-Type': 'application; charset=UTF-8'}
        mBody = {

            "msgtype": "image",
            "image": {
                "base64": s,
                "md5": res1
            }
        }
        r = requests.post(url=url, json=mBody, headers=mHeader)
        print('发送描述返回：',r1.json())
        print('发送二维码返回：',r.json())
        print('======================操作完成======================')





if __name__ == "__main__":
    a = TestFengzi()
    a.setup_method()
    a.test_fengzi()
    a.teardown_method()