# Generated by Selenium IDE
import time
import requests

import sys
f = open('push.log','a')
sys.stdout = f
sys.stderr = f
print('=======这里进入操作：'+time.strftime("%Y-%m-%d, %H:%M:%S")+'===========')
class TestFengzi():
    
    def test_fengzi(self):
        
        url1 = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e8e9d0f9-234f-4bbb-812d-4cac9178c8bf"
        mHeader1 = {'Conrtent-Type': 'application; charset=UTF-8'}
        mBody1 = {
            "msgtype": "markdown",
            "markdown": {
                "content": "<@所有人><font color=\"info\">在开发需求状态如下:</font>[需求列表点击查看>>](https://doc.weixin.qq.com/sheet/e2_AAwAXAZ2AJcnYrmDmrcTC63suSlnh)"
            },
        }
        r1 = requests.post(url=url1, json=mBody1, headers=mHeader1)
        
        print(r1.json())
        print('======================操作完成======================')

if __name__ == "__main__":
    a = TestFengzi()
    a.test_fengzi()